/**
 * Data contract for the Health Score bundle (schema 1.x). Generated by `python -m product.score.export`,
 * consumed by the Next.js app. Prose and rules: product/score/DATA_CONTRACT.md.
 *
 * Rules for consumers
 *  - Ignore unknown fields. A section whose manifest.sections status is not "available" is absent (today only counterparty_entities is "blocked").
 *  - Additive changes bump the minor version (1.1.0), breaking ones the major (2.0.0). Check manifest.schema_version.
 *  - Months are "YYYY-MM" strings, sorted ascending. A missing value is `null`, never NaN or "".
 *  - Money is in the invoice / account currency of the company, not converted (see Company.currency).
 *  - Files are static JSON. Nothing here is a live API.
 */

/* ------------------------------------------------------------------ scores (plan step 2) */

export type Trajectory = "improving" | "stable" | "dip" | "deteriorating" | "insufficient history";
export type Confidence = "high" | "medium" | "low";
/** "dark": no bank booking for 60 days, score capped at 30. "fading": inflows collapsed, capped at 50. */
export type Guard = "dark" | "fading";
export type CategoryId = "payment_history" | "amounts_owed" | "stability" | "new_credit" | "mix";
export type ItemId =
  | "delay_paid" | "delay_coll" | "ap_overdue30" | "ar_overdue30"
  | "runway" | "neg_liq" | "neg_episodes" | "ds_ratio" | "fc_ratio"
  | "months_observed" | "active_share" | "out_vol"
  | "ds_increase" | "fc_increase"
  | "cust_tail" | "credit_note";
export type Unit = "days" | "share" | "share_of_inflows" | "months" | "months_of_6" | "count" | "ratio";

/** manifest.json — read first. */
export interface Manifest {
  schema_version: string;
  scorecard_version: string;
  generated_at: string; // ISO UTC
  as_of_month: string; // last scored month
  months: string[]; // every month that has a score for at least one company; index rows are aligned to it
  detail_months: number; // months (back from as_of_month) that carry items/reasons/attribution
  detail_from_month: string;
  counts: { companies: number; groups: number; company_months: number };
  is_sample: boolean;
  reference: { fitted_on: string; n_companies: number; n_company_months: number };
  source: { input_files: Record<string, string>; dq_log_rules_with_rows: number };
  sections: Record<SectionId, { status: "available" | "planned" | "blocked"; plan_step?: number; files?: string[]; note?: string }>;
  monitor: {
    params_fitted_on: string; // "train companies only"
    floors: Record<string, number>; // chart floors in score points
    method: { name: string; params: Record<string, number | string> };
    material_points: Record<string, number>; // an alert needs the smoothed level this far from the baseline
    forecast_method: "smoothed_level" | "naive_last";
  }; // 1.1.0
  spec: Spec;
  disclaimer: string; // show it where the score is shown; the score is not a predictor
  files: Record<string, { bytes?: number; sha256: string; count?: number }>;
}
export type SectionId =
  | "scores" | "groups" | "control_charts" | "clusters" | "alerts" | "forecast" | "owners_actions" | "counterparty_entities";

/** What the score is made of. Use it for labels, weights and tooltips instead of hard-coding them. */
export interface Spec {
  categories: Record<CategoryId, { label: string; nominal_weight: number; effective_weight: number }>;
  items: { id: ItemId; category: CategoryId; label: string; higher_is_better: boolean; unit: Unit; kind: "pct" | "fixed"; why: string }[];
  guard: { dark_no_booking_days: number; cap_dark: number; fading_inflow_ratio: number; cap_fading: number };
  trajectory: { states: Trajectory[]; slope3_material: number; slope6_material: number; persist_months: number };
  confidence: { levels: Confidence[]; high_min_coverage: number; medium_min_coverage: number; high_min_months: number; low_below_months: number };
  score_needs_months: number;
}

/** companies.json — the list/portfolio view. One row per scored company at its latest month. */
export interface CompanyIndex {
  schema_version: string;
  as_of_month: string;
  months: string[];
  companies: CompanyIndexRow[];
}
export interface CompanyIndexRow {
  company_id: string;
  group_id: string | null;
  latest_month: string;
  score: number; // 0-100, 100 = healthiest
  trajectory: Trajectory;
  confidence: Confidence;
  guard: Guard | null;
  delta_1m: number | null;
  delta_3m: number | null;
  top_reason: string | null; // first "why the score is not higher" sentence
  cluster_id: string | null; // 1.1.0, key of clusters.json; null when the trail is under 6 months
  n_alerts: number; // alerts of this company in the feed window (alerts.json)
  max_alert_severity: AlertSeverity | null;
  scores: (number | null)[]; // aligned with `months`, for sparklines
}

/** companies/{company_id}.json — everything for one company. */
export interface CompanyDetail {
  schema_version: string;
  entity_type: "company";
  company_id: string;
  group_id: string | null;
  country: string | null; // ISO-2 when known
  currency: string | null;
  erp: string | null;
  first_month: string; // first month with any bank transaction
  latest_month: string;
  months: MonthRecord[]; // scored months only, ascending
  // 1.1.0 (steps 3-4). Absent when there is not enough history (cluster: under 6 months; control: under 7 scored months; forecast: under 4).
  cluster?: ClusterMembership;
  control?: ControlChart[]; // own_history for score and three categories, cluster gap for the score
  forecast?: Forecast;
  alert_ids: string[]; // keys into alerts.json, in the feed window
}

export interface MonthRecord {
  month: string;
  score: number; // after the guard cap
  score_pre_cap: number;
  guard: Guard | null;
  guard_adjustment: number; // score - score_pre_cap, <= 0
  trajectory: Trajectory;
  slope3: number | null; // points per month
  slope6: number | null;
  confidence: Confidence;
  confidence_note: string | null; // why not high, ";"-separated
  coverage: number; // share of category weight that exists for this company-month
  trail_months: number;
  categories: Record<CategoryId, { score: number | null; contribution: number }>; // contribution: points of the 100
  // present only for the last `manifest.detail_months` months:
  items?: Partial<Record<ItemId, ItemResult>>; // only items available this month
  reasons?: Reason[]; // up to 4, why the score is not higher, largest points lost first
  change_reasons?: Reason[]; // up to 4, why it moved since last month, largest |points| first
  change_guard?: number | null; // effect of the cap on the change
}
/** sum(items[*].contribution) + guard_adjustment == score (rounding < 0.15). Sum of delta + change_guard == score change. */
export interface ItemResult {
  value: number | null; // in spec unit
  points: number; // 0-100 item score
  contribution: number; // points of the 100 this item brings
  delta: number | null; // change of contribution since last month
}
export interface Reason {
  item: ItemId | "guard" | "top_customer"; // top_customer: only in top_customer_quiet alerts (points 0: not a score input)
  label: string;
  points: number; // reasons: negative = points lost; change_reasons: signed change
  value: number | null;
  unit: Unit | null;
  eur: number | null; // the amount behind it, currency of the company; null when the item has none
  sentence: string; // English, ready to show. Structured fields let the UI template other languages.
}

/** groups.json */
export interface GroupIndex {
  schema_version: string;
  as_of_month: string;
  months: string[];
  groups: {
    group_id: string;
    company_ids: string[];
    n_companies: number;
    latest_mean_score: number | null;
    latest_min_score: number | null;
    latest_min_company_id: string | null;
    mean_scores: (number | null)[]; // aligned with months
    limits_available: boolean; // 1.1.0: true from 3 scored members. Below that, draw only the mean, no limits and no alerts
    control: ControlChart[] | null; // group_own_history (floor grows as the group gets smaller) and group_vs_groups (funnel on the 3-month change)
    alert_ids: string[];
  }[]; // median group has 2 companies: do not draw limits or clusters for tiny groups
}

/* ------------------------------------------------------------------ monitor and forecast (plan steps 3-5, schema 1.1.0) */

export type EntityType = "company" | "group" | "customer" | "supplier"; // customer/supplier: blocked until counterparty IDs map to companies

/** clusters.json: behaviour clusters fitted on train, size signal regressed out. CompanyDetail.cluster points into it. */
export interface ClusterIndex {
  schema_version: string;
  clusters: { cluster_id: string; label: string; description: string; n_companies: number; n_companies_train_fit: number }[];
  quality: { silhouette: Record<string, number>; chosen_k: number; note: string }; // weak structure: show as peers, not segments
}
export interface ClusterMembership {
  cluster_id: string;
  month: string; // the month the comparison is for (the company's latest)
  /** where the company sits among its cluster's train company-months. percentile 100 = healthiest. */
  vs_cluster: { metric: "score" | CategoryId; percentile: number | null; robust_z: number | null }[];
}

/** Plan step 3. Robust EWMA/CUSUM (median/MAD) on within-company change. Four comparisons. */
export type Comparison = "own_history" | "cluster" | "group_own_history" | "group_vs_groups";
export interface ControlChart {
  comparison: Comparison; // "cluster" charts the company's gap to its cluster median (a change of relative standing)
  metric: "score" | CategoryId;
  months: string[]; // trimmed to the months where the chart exists (needs 7 scored months)
  values: (number | null)[]; // group_vs_groups: the 3-month change of the group mean
  center: (number | null)[]; // lagged median (own history) or the median change of groups (group_vs_groups)
  lower: (number | null)[];
  upper: (number | null)[]; // funnel-style limits for groups (widen for small n)
  ewma?: (number | null)[]; // smoothed level, in the units of `values`; the EWMA limit is lower/upper
  cusum_low?: (number | null)[];
  cusum_high?: (number | null)[];
  signal: ("none" | "low" | "high")[]; // raw signal per month
  persistent: boolean[]; // true when the persistence rule holds (3 of the last 4 months signal the same way); alerts start here, and only when also material
  method: { name: string; params: Record<string, number | string> };
}

/**
 * alerts.json: the proactive feed. An alert is the ONSET of a persistent, material move (a company that stays low does not alert every month).
 * Two-sided: improving companies alert too (direction "opportunity"). Group alerts reuse the score kinds with entity.type "group".
 * Wording fixed by the plan for "top_customer_quiet": "top customer stopped billing, review exposure and collections", never "revenue at risk".
 */
export type AlertSeverity = "info" | "watch" | "act";
export type AlertKind =
  | "score_deterioration" | "score_improvement" | "category_drop" | "going_dark" | "top_customer_quiet";
export type Owner = "treasurer" | "cfo" | "collections";
export interface Alert {
  alert_id: string;
  entity: { type: EntityType; id: string; name?: string | null };
  month: string;
  kind: AlertKind;
  direction: "risk" | "opportunity";
  severity: AlertSeverity; // score/category: distance from the baseline (12 / 20 points); going_dark always act; top_customer_quiet: act = top decile of the ranking model, info = billed in all of the last 3 months
  title: string;
  summary: string;
  reasons: Reason[]; // up to 4. Score alerts: the items that moved most since the baseline (points = change of contribution). Groups: empty, see evidence
  persistence: { rule: string; months_flagged: number }; // dips that do not persist are not alerts
  owner: Owner; // who gets it (treasurer = tesorero, collections = Cobros)
  action: string; // concrete recommendation
  evidence: Record<string, number | string | boolean | null>; // top_customer_quiet: counterparty_id, share_last_quarter, last_quarter_amount, months_billed_of_last_3, months_quiet, open_receivable_eur. Score alerts: score, baseline, gap_points. Groups: n_companies, members_moving_most, outside_funnel_vs_other_groups
  rank_score: number | null; // top_customer_quiet only: ranking model score, for ordering, never shown as a probability
}
export interface AlertFeed {
  schema_version: string;
  as_of_month: string;
  from_month: string; // the feed covers the detail window (manifest.detail_from_month .. as_of_month)
  /** Measured on train companies (analysis/monitor/evaluation.md). Quote them next to the alerts; do not round them into claims. */
  stats: {
    false_alarm_rate: number | null; // score-fall alerts not followed by an accepted outcome within 6 months, mean over the eight outcomes
    false_alarm_rate_at_chance: number | null; // the same for an alert on a random month: the two are about equal
    median_lead_time_months: number | null;
    top_customer_precision: number | null; // share of top_customer_quiet onsets where the customer was lost in the next months
    top_customer_base_rate: number | null;
    alerts_per_company_year: number | null;
    note: string;
  };
  alerts: Alert[]; // newest month first, then severity, then rank_score
}

/** Fan chart, not a point estimate. A tie with the naive last value (method "naive_last" ships today), so show it as "where the score usually goes from here". */
export interface Forecast {
  metric: "score";
  method: "smoothed_level" | "naive_last";
  origin_month: string;
  horizon_months: number;
  note: string;
  points: { month: string; median: number; lo50: number; hi50: number; lo80: number; hi80: number }[];
  naive_last: number;
  skill_vs_naive: number | null; // CV skill of the smoothed level over the naive last value at 3 months; ~0 is the honest result
}
