-- Cleaned source tables. Natural keys may be missing or collide on a future
-- CSV drop, so fact tables use surrogate primary keys.

CREATE TABLE IF NOT EXISTS core.groups (
  group_id text PRIMARY KEY,
  erp text,
  n_companies_in_sample integer
);

CREATE TABLE IF NOT EXISTS core.companies (
  company_id text PRIMARY KEY,
  group_id text REFERENCES core.groups (group_id),
  country text,
  currency text,
  erp text,
  created_at timestamptz
);

-- Common product entity: banking + debt (+ unknown ids seen on tx/balances).
-- product_id is unique in this snapshot (banking ∩ debt = ∅) but is not the PK
-- so a later overlapping id can be stored as a second family row.
CREATE TABLE IF NOT EXISTS core.products (
  product_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL,
  company_id text REFERENCES core.companies (company_id),
  family text NOT NULL CHECK (family IN ('banking', 'debt', 'unknown')),
  label text,
  type text,
  bank_name text,
  service text,
  currency text,
  created_at timestamptz,
  granted double precision,
  outstanding double precision,
  liquidity double precision,
  created_after_snapshot boolean,
  outstanding_gt_granted boolean,
  UNIQUE (product_id, family)
);

CREATE UNIQUE INDEX IF NOT EXISTS products_natural_id_uidx
  ON core.products (product_id);

CREATE TABLE IF NOT EXISTS core.debt_schedule (
  schedule_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL,
  company_id text REFERENCES core.companies (company_id),
  settlement_product_id text,
  currency text,
  amortization_type text,
  interest_calc_method text,
  amortising_frequency text,
  granted_balance double precision,
  outstanding_balance double precision,
  total_periods integer,
  next_payment_date timestamptz,
  last_payment_date timestamptz,
  annual_interest_rate_or_spread double precision,
  interest_type text,
  outstanding_gt_granted boolean
);

-- Synthesized from transactions/invoices. Never treated as a scored company.
CREATE TABLE IF NOT EXISTS core.counterparties (
  counterparty_id text PRIMARY KEY,
  seen_in_transactions boolean NOT NULL DEFAULT false,
  seen_in_invoices boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS core.balances (
  balance_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL,
  company_id text REFERENCES core.companies (company_id),
  as_of_date date,
  balance double precision,
  granted double precision,
  liquidity double precision,
  countable double precision,
  balance_sentinel boolean,
  product_known boolean
);

CREATE TABLE IF NOT EXISTS core.transactions (
  tx_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id text,
  company_id text NOT NULL REFERENCES core.companies (company_id),
  product_id text NOT NULL,
  booked_at timestamptz NOT NULL,
  value_date timestamptz,
  amount double precision NOT NULL,
  exchange_rate double precision,
  status text,
  accounting_status text,
  category text,
  description text,
  counterparty_id text,
  is_dup boolean,
  is_extreme boolean,
  product_known boolean,
  out_of_window boolean
);

CREATE TABLE IF NOT EXISTS core.invoices (
  invoice_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id text,
  company_id text NOT NULL REFERENCES core.companies (company_id),
  document_type text,
  issuance_date timestamptz NOT NULL,
  due_date timestamptz,
  payment_date timestamptz,
  amount double precision NOT NULL,
  pending_amount double precision,
  currency text,
  accounting_currency text,
  exchange_rate double precision,
  status text,
  concept text,
  counterparty_id text,
  payment_date_invalid boolean,
  is_extreme boolean,
  issued_after_snapshot boolean
);

CREATE TABLE IF NOT EXISTS core.dq_log (
  dq_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  issue text NOT NULL,
  action text NOT NULL,
  rows_affected bigint,
  source text NOT NULL,
  rows_in_raw_table bigint,
  pct double precision
);

CREATE TABLE IF NOT EXISTS core.load_batches (
  batch_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  loaded_at timestamptz NOT NULL DEFAULT now(),
  source_duckdb text,
  note text
);
