-- Computed score bundle, versioned by run.

CREATE TABLE IF NOT EXISTS analytics.score_runs (
  run_id uuid PRIMARY KEY,
  schema_version text NOT NULL,
  scorecard_version text NOT NULL,
  generated_at timestamptz NOT NULL,
  as_of_month text NOT NULL,
  months text[] NOT NULL,
  detail_months integer NOT NULL,
  detail_from_month text,
  is_sample boolean NOT NULL,
  n_companies integer NOT NULL,
  n_groups integer NOT NULL,
  n_company_months integer NOT NULL,
  source jsonb NOT NULL,
  spec jsonb NOT NULL,
  monitor jsonb NOT NULL,
  sections jsonb NOT NULL,
  reference jsonb,
  files jsonb,
  disclaimer text NOT NULL,
  loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS analytics.clusters (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  cluster_id text NOT NULL,
  label text NOT NULL,
  description text,
  n_companies integer,
  n_companies_train_fit integer,
  PRIMARY KEY (run_id, cluster_id)
);

CREATE TABLE IF NOT EXISTS analytics.cluster_quality (
  run_id uuid PRIMARY KEY REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  chosen_k integer,
  silhouette jsonb,
  note text
);

CREATE TABLE IF NOT EXISTS analytics.company_profiles (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  group_id text,
  country text,
  currency text,
  erp text,
  first_month text,
  latest_month text,
  cluster_id text,
  alert_ids text[] NOT NULL DEFAULT '{}',
  PRIMARY KEY (run_id, company_id)
);

CREATE TABLE IF NOT EXISTS analytics.company_index (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  group_id text,
  latest_month text NOT NULL,
  score double precision NOT NULL,
  trajectory text NOT NULL,
  confidence text NOT NULL,
  guard text,
  delta_1m double precision,
  delta_3m double precision,
  top_reason text,
  cluster_id text,
  n_alerts integer,
  max_alert_severity text,
  sparkline double precision[],
  PRIMARY KEY (run_id, company_id)
);

CREATE TABLE IF NOT EXISTS analytics.company_scores (
  score_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  month text NOT NULL,
  score double precision NOT NULL,
  score_pre_cap double precision NOT NULL,
  guard text,
  guard_adjustment double precision,
  trajectory text NOT NULL,
  slope3 double precision,
  slope6 double precision,
  confidence text NOT NULL,
  confidence_note text,
  coverage double precision,
  trail_months integer,
  change_guard double precision,
  UNIQUE (run_id, company_id, month)
);

CREATE TABLE IF NOT EXISTS analytics.score_categories (
  score_id bigint NOT NULL REFERENCES analytics.company_scores (score_id) ON DELETE CASCADE,
  category_id text NOT NULL,
  score double precision,
  contribution double precision NOT NULL,
  PRIMARY KEY (score_id, category_id)
);

CREATE TABLE IF NOT EXISTS analytics.score_items (
  score_id bigint NOT NULL REFERENCES analytics.company_scores (score_id) ON DELETE CASCADE,
  item_id text NOT NULL,
  value double precision,
  points double precision NOT NULL,
  contribution double precision NOT NULL,
  delta double precision,
  PRIMARY KEY (score_id, item_id)
);

CREATE TABLE IF NOT EXISTS analytics.score_reasons (
  reason_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  score_id bigint NOT NULL REFERENCES analytics.company_scores (score_id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('level', 'change')),
  position smallint NOT NULL,
  item text NOT NULL,
  label text,
  points double precision NOT NULL,
  value double precision,
  unit text,
  eur double precision,
  sentence text NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.company_cluster (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  cluster_id text NOT NULL,
  month text NOT NULL,
  PRIMARY KEY (run_id, company_id)
);

CREATE TABLE IF NOT EXISTS analytics.cluster_vs (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  metric text NOT NULL,
  percentile double precision,
  robust_z double precision,
  PRIMARY KEY (run_id, company_id, metric)
);

CREATE TABLE IF NOT EXISTS analytics.control_charts (
  chart_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  entity_type text NOT NULL CHECK (entity_type IN ('company', 'group')),
  entity_id text NOT NULL,
  comparison text NOT NULL,
  metric text NOT NULL,
  months text[] NOT NULL,
  values double precision[],
  center double precision[],
  lower double precision[],
  upper double precision[],
  ewma double precision[],
  cusum_low double precision[],
  cusum_high double precision[],
  signal text[],
  persistent boolean[],
  method jsonb
);

CREATE TABLE IF NOT EXISTS analytics.forecasts (
  forecast_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  company_id text NOT NULL,
  metric text NOT NULL DEFAULT 'score',
  method text NOT NULL,
  origin_month text NOT NULL,
  horizon_months integer NOT NULL,
  naive_last double precision,
  skill_vs_naive double precision,
  note text,
  UNIQUE (run_id, company_id, metric)
);

CREATE TABLE IF NOT EXISTS analytics.forecast_points (
  forecast_id bigint NOT NULL REFERENCES analytics.forecasts (forecast_id) ON DELETE CASCADE,
  month text NOT NULL,
  median double precision NOT NULL,
  lo50 double precision NOT NULL,
  hi50 double precision NOT NULL,
  lo80 double precision NOT NULL,
  hi80 double precision NOT NULL,
  PRIMARY KEY (forecast_id, month)
);

CREATE TABLE IF NOT EXISTS analytics.alerts (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  alert_id text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  entity_name text,
  month text NOT NULL,
  kind text NOT NULL,
  direction text NOT NULL,
  severity text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  owner text NOT NULL,
  action text NOT NULL,
  persistence_rule text,
  months_flagged integer,
  rank_score double precision,
  evidence jsonb,
  PRIMARY KEY (run_id, alert_id)
);

CREATE TABLE IF NOT EXISTS analytics.alert_reasons (
  run_id uuid NOT NULL,
  alert_id text NOT NULL,
  position smallint NOT NULL,
  item text,
  label text,
  points double precision,
  value double precision,
  unit text,
  eur double precision,
  sentence text,
  PRIMARY KEY (run_id, alert_id, position),
  FOREIGN KEY (run_id, alert_id) REFERENCES analytics.alerts (run_id, alert_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analytics.groups_index (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  group_id text NOT NULL,
  n_companies integer NOT NULL,
  latest_mean_score double precision,
  latest_min_score double precision,
  latest_min_company_id text,
  mean_scores double precision[],
  limits_available boolean,
  alert_ids text[] NOT NULL DEFAULT '{}',
  PRIMARY KEY (run_id, group_id)
);

CREATE TABLE IF NOT EXISTS analytics.group_members (
  run_id uuid NOT NULL REFERENCES analytics.score_runs (run_id) ON DELETE CASCADE,
  group_id text NOT NULL,
  company_id text NOT NULL,
  PRIMARY KEY (run_id, group_id, company_id)
);

-- Staging for COPY (natural keys). Truncated on each load, never queried by the app.
CREATE UNLOGGED TABLE IF NOT EXISTS analytics.stg_score_categories (
  run_id uuid,
  company_id text,
  month text,
  category_id text,
  score double precision,
  contribution double precision
);
CREATE UNLOGGED TABLE IF NOT EXISTS analytics.stg_score_items (
  run_id uuid,
  company_id text,
  month text,
  item_id text,
  value double precision,
  points double precision,
  contribution double precision,
  delta double precision
);
CREATE UNLOGGED TABLE IF NOT EXISTS analytics.stg_score_reasons (
  run_id uuid,
  company_id text,
  month text,
  kind text,
  position smallint,
  item text,
  label text,
  points double precision,
  value double precision,
  unit text,
  eur double precision,
  sentence text
);
CREATE UNLOGGED TABLE IF NOT EXISTS analytics.stg_forecast_points (
  run_id uuid,
  company_id text,
  month text,
  median double precision,
  lo50 double precision,
  hi50 double precision,
  lo80 double precision,
  hi80 double precision
);
