/**
 * Data contract for the Health Score bundle (schema 1.x). Generated by `python -m product.score.export`,
 * consumed by the Next.js app. Prose and rules: product/score/DATA_CONTRACT.md.
 *
 * Rules for consumers
 *  - Ignore unknown fields. Treat every field marked "planned" as absent until manifest.sections says "available".
 *  - Additive changes bump the minor version (1.1.0), breaking ones the major (2.0.0). Check manifest.schema_version.
 *  - Months are "YYYY-MM" strings, sorted ascending. A missing value is `null`, never NaN or "".
 *  - Money is in the invoice / account currency of the company, not converted (see Company.currency).
 *  - Files are static JSON. Nothing here is a live API.
 */

/* ------------------------------------------------------------------ available today (plan step 2) */

export type Trajectory = "improving" | "stable" | "dip" | "deteriorating" | "insufficient history";
export type Confidence = "high" | "medium" | "low";
/** "dark": no bank booking for 60 days, score capped at 30. "fading": inflows collapsed, capped at 50. */
export type Guard = "dark" | "fading";
export type CategoryId = "payment_history" | "amounts_owed" | "stability" | "new_credit" | "mix";
export type ItemId =
  | "delay_paid" | "delay_coll" | "ap_overdue30" | "ar_overdue30"
  | "runway" | "neg_liq" | "neg_episodes" | "ds_ratio" | "fc_ratio"
  | "months_observed" | "active_share" | "out_vol"
  | "ds_increase" | "fc_increase"
  | "cust_tail" | "credit_note";
export type Unit = "days" | "share" | "share_of_inflows" | "months" | "months_of_6" | "count" | "ratio";

/** manifest.json — read first. */
export interface Manifest {
  schema_version: string;
  scorecard_version: string;
  generated_at: string; // ISO UTC
  as_of_month: string; // last scored month
  months: string[]; // every month that has a score for at least one company; index rows are aligned to it
  detail_months: number; // months (back from as_of_month) that carry items/reasons/attribution
  detail_from_month: string;
  counts: { companies: number; groups: number; company_months: number };
  is_sample: boolean;
  reference: { fitted_on: string; n_companies: number; n_company_months: number };
  source: { input_files: Record<string, string>; dq_log_rules_with_rows: number };
  sections: Record<SectionId, { status: "available" | "planned" | "blocked"; plan_step?: number; files?: string[]; note?: string }>;
  spec: Spec;
  disclaimer: string; // show it where the score is shown; the score is not a predictor
  files: Record<string, { bytes?: number; sha256: string; count?: number }>;
}
export type SectionId =
  | "scores" | "groups" | "control_charts" | "clusters" | "alerts" | "forecast" | "owners_actions" | "counterparty_entities";

/** What the score is made of. Use it for labels, weights and tooltips instead of hard-coding them. */
export interface Spec {
  categories: Record<CategoryId, { label: string; nominal_weight: number; effective_weight: number }>;
  items: { id: ItemId; category: CategoryId; label: string; higher_is_better: boolean; unit: Unit; kind: "pct" | "fixed"; why: string }[];
  guard: { dark_no_booking_days: number; cap_dark: number; fading_inflow_ratio: number; cap_fading: number };
  trajectory: { states: Trajectory[]; slope3_material: number; slope6_material: number; persist_months: number };
  confidence: { levels: Confidence[]; high_min_coverage: number; medium_min_coverage: number; high_min_months: number; low_below_months: number };
  score_needs_months: number;
}

/** companies.json — the list/portfolio view. One row per scored company at its latest month. */
export interface CompanyIndex {
  schema_version: string;
  as_of_month: string;
  months: string[];
  companies: CompanyIndexRow[];
}
export interface CompanyIndexRow {
  company_id: string;
  group_id: string | null;
  latest_month: string;
  score: number; // 0-100, 100 = healthiest
  trajectory: Trajectory;
  confidence: Confidence;
  guard: Guard | null;
  delta_1m: number | null;
  delta_3m: number | null;
  top_reason: string | null; // first "why the score is not higher" sentence
  scores: (number | null)[]; // aligned with `months`, for sparklines
}

/** companies/{company_id}.json — everything for one company. */
export interface CompanyDetail {
  schema_version: string;
  entity_type: "company";
  company_id: string;
  group_id: string | null;
  country: string | null; // ISO-2 when known
  currency: string | null;
  erp: string | null;
  first_month: string; // first month with any bank transaction
  latest_month: string;
  months: MonthRecord[]; // scored months only, ascending
  // planned (see below): cluster?, control?, forecast?, alert_ids?
  cluster?: ClusterMembership;
  control?: ControlChart[];
  forecast?: Forecast;
  alert_ids?: string[];
}

export interface MonthRecord {
  month: string;
  score: number; // after the guard cap
  score_pre_cap: number;
  guard: Guard | null;
  guard_adjustment: number; // score - score_pre_cap, <= 0
  trajectory: Trajectory;
  slope3: number | null; // points per month
  slope6: number | null;
  confidence: Confidence;
  confidence_note: string | null; // why not high, ";"-separated
  coverage: number; // share of category weight that exists for this company-month
  trail_months: number;
  categories: Record<CategoryId, { score: number | null; contribution: number }>; // contribution: points of the 100
  // present only for the last `manifest.detail_months` months:
  items?: Partial<Record<ItemId, ItemResult>>; // only items available this month
  reasons?: Reason[]; // up to 4, why the score is not higher, largest points lost first
  change_reasons?: Reason[]; // up to 4, why it moved since last month, largest |points| first
  change_guard?: number | null; // effect of the cap on the change
}
/** sum(items[*].contribution) + guard_adjustment == score (rounding < 0.15). Sum of delta + change_guard == score change. */
export interface ItemResult {
  value: number | null; // in spec unit
  points: number; // 0-100 item score
  contribution: number; // points of the 100 this item brings
  delta: number | null; // change of contribution since last month
}
export interface Reason {
  item: ItemId | "guard";
  label: string;
  points: number; // reasons: negative = points lost; change_reasons: signed change
  value: number | null;
  unit: Unit | null;
  eur: number | null; // the amount behind it, currency of the company; null when the item has none
  sentence: string; // English, ready to show. Structured fields let the UI template other languages.
}

/** groups.json */
export interface GroupIndex {
  schema_version: string;
  as_of_month: string;
  months: string[];
  groups: {
    group_id: string;
    company_ids: string[];
    n_companies: number;
    latest_mean_score: number | null;
    latest_min_score: number | null;
    latest_min_company_id: string | null;
    mean_scores: (number | null)[]; // aligned with months
  }[]; // median group has 2 companies: do not draw limits or clusters for tiny groups
}

/* ------------------------------------------------------------------ planned (not in bundles yet) */

export type EntityType = "company" | "group" | "customer" | "supplier"; // customer/supplier: blocked until counterparty IDs map to companies

/** Plan step 3. clusters.json: behaviour clusters fitted on train (not size). CompanyDetail.cluster points into it. */
export interface ClusterIndex {
  schema_version: string;
  clusters: { cluster_id: string; label: string; description: string; n_companies: number }[];
}
export interface ClusterMembership {
  cluster_id: string;
  vs_cluster: { metric: "score" | CategoryId; percentile: number | null; robust_z: number | null }[];
}

/** Plan step 3. Robust EWMA/CUSUM (median/MAD) on within-company change. Four comparisons. */
export type Comparison = "own_history" | "cluster" | "group_own_history" | "group_vs_groups";
export interface ControlChart {
  comparison: Comparison;
  metric: "score" | CategoryId;
  months: string[];
  values: (number | null)[];
  center: number | (number | null)[];
  lower: (number | null)[];
  upper: (number | null)[]; // funnel-style limits for groups (widen for small n)
  ewma?: (number | null)[];
  cusum_low?: (number | null)[];
  cusum_high?: (number | null)[];
  signal: ("none" | "low" | "high")[]; // raw signal per month
  persistent: boolean[]; // true when the persistence rule holds (e.g. 3 of the last 4 months)
  method: { name: string; params: Record<string, number | string> };
}

/**
 * Plan steps 3 and 5. alerts.json: the proactive feed. Two-sided: improving companies alert too (direction "opportunity").
 * Alert wording is fixed by the plan for "top_customer_quiet": "top customer stopped billing, review exposure and collections",
 * never "revenue at risk".
 */
export type AlertKind =
  | "score_deterioration" | "score_improvement" | "category_drop" | "going_dark" | "top_customer_quiet";
export type Owner = "treasurer" | "cfo" | "collections";
export interface Alert {
  alert_id: string;
  entity: { type: EntityType; id: string; name?: string | null };
  month: string;
  kind: AlertKind;
  direction: "risk" | "opportunity";
  severity: "info" | "watch" | "act";
  title: string;
  summary: string;
  reasons: Reason[]; // same shape as score reasons, with eur
  persistence: { rule: string; months_flagged: number }; // dips that do not persist are not alerts
  owner: Owner | null; // step 5: who gets it
  action: string | null; // step 5: concrete recommendation
  evidence: Record<string, number | string | null>; // e.g. top_customer_quiet: counterparty_id, share_last_quarter, months_quiet, open_receivable_eur
  rank_score: number | null; // ranking only (the night's model score for top_customer_quiet), never shown as a probability
}
export interface AlertFeed {
  schema_version: string;
  as_of_month: string;
  stats: { false_alarm_rate: number | null; median_lead_time_months: number | null; note: string }; // measured on train, quoted with the alert
  alerts: Alert[];
}

/** Plan step 4. Fan chart, not a point estimate. Expect a tie with the naive last value; show the baseline. */
export interface Forecast {
  metric: "score";
  method: "smoothed_level" | "naive_last";
  origin_month: string;
  horizon_months: number;
  points: { month: string; median: number; lo50: number; hi50: number; lo80: number; hi80: number }[];
  naive_last: number;
  skill_vs_naive: number | null; // group-fold CV; ~0 is the expected honest result
}
